### ISSUE TITLE
Add support of users

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#68]
Add support of users: 
- [x] Authentication (sign in and sign out) #86 
- [x] Registration #81 
- [x] Confirmation of registration #84
- [x] Reset password.
- [x] Automatically refresh outdated tokens. #95

**Comment by blackst0ne** [comment]
@jamm1985 right now on [the registration page](https://eqalert.ru/ru/users/sign_up) we have such text: 

![screenshot_20180202_102245](https://user-images.githubusercontent.com/1610813/35708647-2d9000ac-0803-11e8-900a-6eb6ec5ade2b.png)

We do not have support of data export in SEISAN format. 

What are we going to do in the 2.0 release with this text? 
Should we remove the SEISAN mention from there?

**Comment by blackst0ne** [comment]
@jamm1985 

One more question.
API gives all the messages in English. 
eqalert.ru now supports only Russian. 

What should we show if API gives an error back to a client? 
1. A message in English? 
2. A message in Russian?

**Comment by blackst0ne** [comment]
Ping @jamm1985

**Comment by jamm1985** [comment]
> Should we remove the SEISAN mention from there?
Please remove the SEISAN mention from there.

> What should we show if API gives an error back to a client?
Russian users should get messages in Russian.

**Comment by blackst0ne** [comment]
@jamm1985 

> Russian users should get messages in Russian. 

Should users get the same messages in Russian on all the clients (website, ios, android)? 
If so, we should add Russian translations to `seismo-api`.

**Comment by jamm1985** [comment]
I don't sure about translations on seismo-api side. I think it is frontend (client) side. The specific messages can be different for a each one client.

Furthermore, theoretically we can have another one client, for example, for Vietnam. Your logic will require add Vietnam's translations on api...

**Comment by blackst0ne** [comment]
If we are about consistency, then there should be only one source of truth.

**Comment by jamm1985** [comment]
I suggest do not show for users pure errors from API. I think that forms errors checking have to be done by UI BEFORE the data go to API.

Furthermore, I suggest to suppress pure API messages from user. I case of getting any errors from API side we have to implement some error reporting procedure to dev group. This way allow us to do UI better at all.

**Comment by blackst0ne** [comment]
@jamm1985 there are two validation layers: both on frontend and on backend.

I've added validations to the frontend part. That means that all frontend-possible checks are done **before** any data gets sent.   
But backend does its checks too.   
For example, the most possible error would be `email has already been taken`.    
This type of errors our clients (webapp, mobile apps, etc) should process and help users understand what was wrong.     

If we're going to translate all that errors on the frontend part, we then have to synchronize all that messages with all our clients to make them all consistent. 
I think the best option is to just send error messages from backend in Russian until we have support of dual languages.

**Comment by jamm1985** [comment]
There are a lot of errors that API can generate. The forwarding any errors to users is not true way because API errors generally contents a technical information.

For example, `email has already been taken` can be show to user like:

`sorry, this email has been taken, please check email field`

OR

`something wrong during registration... Are you already register?`

Also you may need to change the names often for marketing purposes. 

It is possible to implement error codes and technical descriptions on API for correct error handling in UI.

**Comment by blackst0ne** [comment]
@jamm1985 

I am talking about **only validation** error messages.   
API already sends text messages.    
All I want is to receive the same messages in Russian because our clients (applications) talks in Russian.

**Comment by jamm1985** [comment]
There are a lot of errors that API can generate. The forwarding any errors to users is not true way because API errors generally contents a technical information.

For example, `email has already been taken` can be show to user like:

`sorry, this email has been taken, please check email field`

OR

`something wrong during registration... Are you already register?`

Also you may need to change the names often for marketing purposes. 

It is possible to implement error codes and technical descriptions on API for correct error handling in UI.

**Comment by jamm1985** [comment]
The text messages that API send is not intended for end users.

**Comment by jamm1985** [comment]
> It is possible to implement error codes and technical descriptions on API for correct error handling in UI.

I suggest perform error handling by unique codes. @DoctorLines  can implement special method which will be return short text description by code.

**Comment by blackst0ne** [comment]
Implemented.
